# Generated by Django 2.2.6 on 2019-12-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0002_auto_20191221_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_actor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_actor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_actor', to=settings.AUTH_USER_MODEL),
        ),
    ]
